---
  - hosts: localhost
    connection: local
    become: yes
    become_method: sudo
    tasks:
      - name: "Install software"
        apt: name={{ item }} state=present
        with_items:
          - mc
          - git
